language: python
sudo: required
addons:
    chrome: stable
dist: trusty
cache:
    pip: true
    directories:
    - node_modules
python:
    - "2.7"
os:
    - linux
install:
    - npm install
    - pip install -r requirements.txt
stages:
    - lint
    - test
matrix:
    include:
        - name: "npm test"
          env: TEST_CMD="npm run-script test"
          stage: test
        - name: "coverage"
          env: TEST_CMD="coverage run --branch --source='designsafe' manage.py test --settings=designsafe.settings.test_settings --pattern=tests.py && codecov"
          stage: test
        - name: "Flake8"
          env: TEST_CMD="flake8 designsafe"
          stage: lint
        - name: "pylint"
          env: TEST_CMD="pylint designsafe"
          stage: lint
        - name: "pydocstyle"
          env: TEST_CMD="pydocstyle designsafe"
          stage: lint
        - name: "eslint"
          env: TEST_CMD="npm run-script lint"
          stage: lint
    allow_failures:
        - name: "Flake8"
          env: TEST_CMD="flake8 designsafe"
          stage: lint
        - name: "pylint"
          env: TEST_CMD="pylint designsafe"
          stage: lint
        - name: "pydocstyle"
          env: TEST_CMD="pydocstyle designsafe"
          stage: lint
        - name: "eslint"
          env: TEST_CMD="npm run-script lint"
          stage: lint
before_script:
    - find designsafe/settings/* -name *.sample.* | while read line; do cp $line ${line/example\./}; done;
script: $TEST_CMD
