language: python
sudo: required
dist: trusty
cache: pip
python:
    - "2.7"
os:
    - linux
install:
    - npm install
    - pip install -r requirements.txt
stages:
    - lint
    - test
matrix:
    include:
        - name: "Flake8"
          env: TEST_CMD=flake8 designsafe
        - name: "pylint"
          env: TEST_CMD=pylint designsafe
        - name: "pydocstyle"
          env: TEST_CMD=pydocstyle designsafe
        - name: "eslint"
          env: TEST_CMD=eslint designsafe/static/scripts
        - name: "npm test"
          env: TEST_CMD=npm run-script test
        - name: "coverage"
          env: TEST_CMD=coverage run --branch --source="designsafe" manage.py test --pattern=test.py && codecov

script: $TEST_CMD
