# This compose file is useful for debugging with ipdb
---
redis:
  image: redis

elasticsearch:
  image: elasticsearch:2.3.2
  volumes:
    - ./data/elasticsearch:/data
  ports:
    - 9200:9200

mysql:
  image: mysql:5.6
  ports:
    - 3306:3306
  volumes:
    - ./data/mysql:/docker-entrypoint-initdb.d
  environment:
    MYSQL_ROOT_PASSWORD: DS_DEV
    MYSQL_DATABASE: DS_DEV
    MYSQL_USER: DS_DEV
    MYSQL_PASSWORD: DS_DEV

memcached:
  image: memcached

django:
  build: .
  env_file: designsafe.env
  environment:
    - DJANGO_SETTINGS_MODULE=designsafe.http_debug_settings
    # - DATABASE_HOST=mysql
    # - DATABASE_NAME=DS_DEV
    # - DATABASE_PORT=3306
    # - DATABASE_USER=DS_DEV
    # - DATABASE_PASSWORD=DS_DEV
    - DS_LOCAL_DEV=True
  links:
    - redis:redis
    - memcached:memcached
    - elasticsearch:elasticsearch
    - mysql:mysql
  volumes:
    - .:/portal
    - /corral-repl/tacc/NHERI:/corral-repl/tacc/NHERI
    - /var/www/designsafe-ci.org/static
    - /var/www/designsafe-ci.org/media
  ports:
    - 8000:8000
    - 5555:5555
  dns:
    - 8.8.8.8
    - 8.8.4.4
  command: ./bin/run-django.sh

nginx:
  image: nginx
  volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/gzip.conf:/etc/nginx/gzip.conf
    - ./conf/dummy.crt:/etc/ssl/dummy.crt
    - ./conf/dummy.key:/etc/ssl/dummy.key
    - ./conf/dhparam.pem:/etc/ssl/dhparam.pem
  volumes_from:
    - django
  links:
    - django:django
  ports:
    - 80:80
    - 443:443

worker:
  build: .
  env_file: designsafe.env
  environment:
    - DJANGO_SETTINGS_MODULE=designsafe.http_debug_settings
    - DATABASE_HOST=mysql
    - DATABASE_NAME=DS_DEV
    - DATABASE_PORT=3306
    - DATABASE_USER=DS_DEV
    - DATABASE_PASSWORD=DS_DEV
    - DS_LOCAL_DEV=True
  links:
    - redis:redis
    - memcached:memcached
    - elasticsearch:elasticsearch
    - mysql:mysql
  volumes:
    - .:/portal
    - /corral-repl/tacc/NHERI:/corral-repl/tacc/NHERI
  dns:
    - 8.8.8.8
    - 8.8.4.4
  command: ./bin/run-celery-debug.sh
