# This compose file is useful for testing https
---
redis:
    image: redis

django:
  build: .
  env_file: designsafe.env
  links:
    - redis:redis
  volumes:
    - .:/portal
  ports:
    - 8000:8000
  dns:
    - 8.8.8.8
    - 8.8.4.4
  command: python manage.py runserver 0.0.0.0:8000

nginx:
  image: nginx
  volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/dummy.crt:/etc/ssl/dummy.crt
    - ./conf/dummy.key:/etc/ssl/dummy.key
  volumes_from:
    - django
  links:
    - django:django
  ports:
    - 80:80
    - 443:443
