# This compose file is useful for testing https
---
redis:
  image: redis

django:
  build: .
  env_file: designsafe.env
  environment:
    - DJANGO_SETTINGS_MODULE=designsafe.http_debug_settings
  links:
    - redis:redis
  volumes:
    - .:/portal
    - /var/www/designsafe-ci.org/static
    - /var/www/designsafe-ci.org/media
  ports:
    - 8000:8000
  dns:
    - 8.8.8.8
    - 8.8.4.4
  command: python manage.py runserver 0.0.0.0:8000

#ef:
#  build: .
#  env_file: designsafe.env
#  environment:
#    - DJANGO_SETTINGS_MODULE=designsafe.ef_http_debug_settings
#  links:
#    - redis:redis
#  volumes:
#    - .:/portal
#  dns:
#    - 8.8.8.8
#    - 8.8.4.4
#  command: python manage.py runserver 0.0.0.0:8000

nginx:
  image: nginx
  volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/gzip.conf:/etc/nginx/gzip.conf
    - ./conf/dummy.crt:/etc/ssl/dummy.crt
    - ./conf/dummy.key:/etc/ssl/dummy.key
    - ./conf/dhparam.pem:/etc/ssl/dhparam.pem
  volumes_from:
    - django
  links:
    - django:django
#    - ef:ef
  ports:
    - 80:80
    - 443:443

worker:
  build: .
  env_file: designsafe.env
  environment:
    - DJANGO_SETTINGS_MODULE=designsafe.http_debug_settings
  links:
    - redis:redis
  volumes:
    - .:/portal
  dns:
    - 8.8.8.8
    - 8.8.4.4
  command: ./bin/run-celery-debug.sh
