data:
  image: buildpack-deps:trusty
  volumes:
    - /var/www/designsafe-ci.org/media

django:
  build: .
  env_file: designsafe.env
  volumes:
    - /var/www/designsafe-ci.org/static
  volumes_from:
    - data

nginx:
  image: nginx
  volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
  volumes_from:
    - data
    - django
  links:
    - django:django
  ports:
    - 80:80