data:
  image: buildpack-deps:trusty
  volumes:
    - /designsafe/media:/var/www/designsafe-ci.org/media

django:
  image: designsafeci/portal
  restart: always
  env_file: designsafe.env
  log_driver: syslog
  log_opt:
    syslog-tag: main
  volumes:
    - /var/www/designsafe-ci.org/static
  volumes_from:
    - data

fiu_ef:
  image: designsafeci/portal
  restart: always
  env_file: designsafe.env
  environment:
    DJANGO_SETTINGS_MODULE: designsafe.sites.fiu_ef
  log_driver: syslog
  log_opt:
    syslog-tag: fiu_ef
  volumes_from:
    - data

lehigh_ef:
  image: designsafeci/portal
  restart: always
  env_file: designsafe.env
  environment:
    DJANGO_SETTINGS_MODULE: designsafe.sites.lehigh_ef
  log_driver: syslog
  log_opt:
    syslog-tag: lehigh_ef
  volumes_from:
    - data

oregonstate_ef:
  image: designsafeci/portal
  restart: always
  env_file: designsafe.env
  environment:
    DJANGO_SETTINGS_MODULE: designsafe.sites.oregonstate_ef
  log_driver: syslog
  log_opt:
    syslog-tag: oregonstate_ef
  volumes_from:
    - data

ucdavis_ef:
  image: designsafeci/portal
  restart: always
  env_file: designsafe.env
  environment:
    DJANGO_SETTINGS_MODULE: designsafe.sites.ucdavis_ef
  log_driver: syslog
  log_opt:
    syslog-tag: ucdavis_ef
  volumes_from:
    - data

ucsd_ef:
  image: designsafeci/portal
  restart: always
  env_file: designsafe.env
  environment:
    DJANGO_SETTINGS_MODULE: designsafe.sites.ucsd_ef
  log_driver: syslog
  log_opt:
    syslog-tag: ucsd_ef
  volumes_from:
    - data

ufl_ef:
  image: designsafeci/portal
  restart: always
  env_file: designsafe.env
  environment:
    DJANGO_SETTINGS_MODULE: designsafe.sites.ufl_ef
  log_driver: syslog
  log_opt:
    syslog-tag: ufl_ef
  volumes_from:
    - data

utexas_ef:
  image: designsafeci/portal
  restart: always
  env_file: designsafe.env
  environment:
    DJANGO_SETTINGS_MODULE: designsafe.sites.utexas_ef
  log_driver: syslog
  log_opt:
    syslog-tag: utexas_ef
  volumes_from:
    - data

nginx:
  image: nginx
  restart: always
  log_driver: syslog
  log_opt:
    syslog-tag: nginx
  volumes:
    - /designsafe/certs/main:/etc/ssl/designsafe-ci.org
    - /designsafe/certs/ef:/etc/ssl/ef.designsafe-ci.org
    - /designsafe/portal/conf/nginx-qa.conf:/etc/nginx/nginx.conf
    - /designsafe/portal/conf/robots.txt:/var/www/designsafe-ci.org/robots.txt
  volumes_from:
    - data
    - django
  links:
    - django:django
    - fiu_ef:fiu_ef
    - lehigh_ef:lehigh_ef
    - oregonstate_ef:oregonstate_ef
    - ucdavis_ef:ucdavis_ef
    - ucsd_ef:ucsd_ef
    - ufl_ef:ufl_ef
    - utexas_ef:utexas_ef
  ports:
    - 80:80
    - 443:443