# This compose file is useful for testing https
---
version: "3"
services:
    redis:
      image: redis:3.2
      volumes:
        - ../../data/redis:/data
        - ../redis.conf:/usr/local/etc/redis/redis.conf
      command: bin/run-redis.sh
      container_name: des_redis
      hostname: des_redis

    rabbitmq:
      image: rabbitmq:3.6.10-management
      env_file: ../env_files/rabbitmq.env
      container_name: des_rabbitmq
      hostname: des_rabbitmq

    memcached:
      image: memcached:latest
      container_name: des_memcached
      hostname: des_memcached

    elasticsearch:
      image: elasticsearch:5.5.1
      volumes:
        - ../elasticsearch:/usr/share/elasticsearch/config
        - ../../data/elasticsearch:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      container_name: des_elasticsearch
      hostname: des_elasticsearch

    mysql:
      image: mysql:5.6
      ports:
        - 3306:3306
      env_file: ../env_files/mysql.env
      volumes:
        - ../../data/mysql:/var/lib/mysql
      container_name: des_mysql
      hostname: des_mysql

    nginx:
      image: nginx
      volumes:
        - ../nginx/nginx.conf:/etc/nginx/nginx.conf
        - ../nginx/gzip.conf:/etc/nginx/gzip.conf
        - ../nginx/dummy.crt:/etc/ssl/dummy.crt
        - ../nginx/dummy.key:/etc/ssl/dummy.key
        - ../nginx/dhparam.pem:/etc/ssl/dhparam.pem
      volumes:
        - ../../.:/srv/www/designsafe
        - ../../data/NHERI:/corral-repl/tacc/NHERI
        - ../../data/static:/var/www/designsafe-ci.org/static
        - ../../data/media:/var/www/designsafe-ci.org/media
      links:
        - django:django
      ports:
        - 80:80
        - 443:443
      container_name: des_nginx
      hostname: des_nginx

    django:
      image: designsafeci/portal:local
      env_file: ../env_files/designsafe.env
      links:
        - redis:redis
        - memcached:memcached
      volumes:
        - ../../.:/srv/www/designsafe
        - ../../data/NHERI:/corral-repl/tacc/NHERI
        - ../../data/static:/var/www/designsafe-ci.org/static
        - ../../data/media:/var/www/designsafe-ci.org/media
      ports:
        - 8000:8000
        - 5555:5555
      dns:
        - 8.8.8.8
        - 8.8.4.4
      command: bin/run-django.sh
      container_name: des_django
      hostname: des_django

    workers:
      image: designsafeci/portal:local
      env_file: ../env_files/designsafe.env
      links:
        - redis:redis
        - memcached:memcached
      volumes:
        - ../../.:/srv/www/designsafe
        - ../../data/NHERI:/corral-repl/tacc/NHERI
        - ../../data/static:/var/www/designsafe-ci.org/static
        - ../../data/media:/var/www/designsafe-ci.org/media
      dns:
        - 8.8.8.8
        - 8.8.4.4
      command: bin/run-celery-debug.sh
      container_name: des_workers
      hostname: des_workers
